### PR TITLE
Updates required for Summed ADC changes

### PR DESCRIPTION
**Pull request by amerega**

### CODE REVIEW

**Comment by tomjunk** [comment]
I assume the TO BE FIXED lines were added by a script.  Looks like the CI passed.

**Comment by lgarren** [comment]
DUNE may wish to review the "TO BE FIXED" lines.  The experts may have a different solution.

**Comment by aolivier23** [comment]
I'm planning to try to merge this tomorrow morning when I cut a release for the LArSoft breaking changes.

**Review by aolivier23 — APPROVED** [review]
We're choosing to use only one algorithm for hit ADC for now.

**Pull request merged**
